name: Deploy React Vite App to EC2

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Vite app
        run: |
          npm run build

      - name: Copy files to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.232.218.212
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/your-app-directory
            rm -rf *
            git pull origin main
            cp -r /tmp/build/* . # Copy built files from GitHub Actions runner to EC2
            sudo systemctl restart nginx # Restart Nginx or your web server

      - name: Restart Nginx on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@13.232.218.212 "sudo systemctl restart nginx"
